server:
  port: 8992
spring:
  datasource:
    username: root
    password: abc123...
    url: jdbc:mysql://110.40.209.66:3306/huang_final?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    serialization:
      write-dates-as-timestamps: true
mybatis-plus:
  mapper-locations: com/final_back/mapper/xml/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

