server:
  port: 8991

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/mysql_test?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis-plus:
  mapper-locations: com/final_back/mapper/xml/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0